[package]
name = "rltk_roguelike_by_tutorial"
version = "0.1.0"
authors = ["Mikhail Merzlyutin <merzlyutinme@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "0.8.1" }
